sudo: false
language: node_js
node_js:
  - 'stable'
script:
  - npm run build
after_script:
  - ls -lh dist/bundle.*
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
